# Generated by Django 3.2.15 on 2023-02-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220909_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiringtoken',
            options={'ordering': ['created_date'], 'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AddField(
            model_name='log',
            name='user_agent',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
