# Generated by Django 4.2.3 on 2023-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_treatmentplani18n_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentplan",
            name="randomize",
            field=models.BooleanField(default=False),
        ),
    ]
