# Generated by Django 4.2.3 on 2023-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_treatmentplan_randomize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
