# Generated by Django 4.2.11 on 2024-10-11 18:13

from django.db import migrations, models
import mepp.api.models.exercise


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_exercise_auto_translate_treatmentplan_auto_translate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=mepp.api.models.exercise.upload_to
            ),
        ),
    ]
