# Generated by Django 4.2.11 on 2024-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_alter_category_parent_alter_exercise_auto_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_video',
            field=models.BooleanField(default=True),
        ),
    ]
