# Generated by Django 4.2.11 on 2024-11-01 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mepp.api.fields.uuid


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_user_use_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'modified_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('uid', mepp.api.fields.uuid.UUIDField(uid_prefix='b')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleI18n',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'modified_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('language', models.CharField(default='en', max_length=2)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('external_url', models.URLField(default='')),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='i18n',
                        to='api.article',
                    ),
                ),
            ],
            options={
                'abstract': False,
                'unique_together': {('parent', 'language')},
            },
        ),
    ]
