# Generated by Django 4.2.11 on 2024-11-06 03:36

from django.db import migrations, models
import mepp.api.fields.uuid


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_article_articlei18n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='use_video',
        ),
        migrations.AddField(
            model_name='article',
            name='auto_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_cognitive_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='uid',
            field=mepp.api.fields.uuid.UUIDField(uid_prefix='a'),
        ),
    ]
