# Generated by Django 4.2.11 on 2024-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_remove_user_use_video_article_auto_translate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auto_translate',
            new_name='auto_translate_description',
        ),
        migrations.AddField(
            model_name='article',
            name='auto_translate_title',
            field=models.BooleanField(default=False),
        ),
    ]
