# Generated by Django 4.2.11 on 2024-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0019_article_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='auto_translate',
            field=models.BooleanField(default=False),
        ),
    ]
