# Generated by Django 4.2.16 on 2024-11-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_rename_has_cognitive_issues_user_use_video_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
