# Generated by Django 4.2.16 on 2024-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_alter_category_options_alter_articlei18n_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryi18n',
            options={
                'verbose_name': 'translation',
                'verbose_name_plural': 'translations',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_with_audio',
            field=models.BooleanField(default=False),
        ),
    ]
