# Generated by Django 5.2.12 on 2026-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_categoryi18n_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryi18n',
            unique_together=set(),
        ),
    ]
